import { Flame, Heart, Leaf, Truck } from 'lucide-react';
import { restaurant } from '../../config/restaurant';
import { SectionLabel } from '../ui/SectionHeading';
import { FallbackImage } from '../ui/FallbackImage';
const icons = { flame: Flame, leaf: Leaf, heart: Heart, truck: Truck };
export function AboutSection() { return <section id="about" className="bg-background py-20 sm:py-24 px-5"><div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
  <div><SectionLabel>{restaurant.about.eyebrow}</SectionLabel><h2 className="font-display text-4xl sm:text-5xl font-black text-heading leading-tight">{restaurant.about.heading}<span className="block text-accent">{restaurant.about.highlightedHeading}</span></h2><p className="text-muted mt-6 leading-relaxed">{restaurant.about.description}</p><p className="text-muted mt-4 leading-relaxed">{restaurant.about.secondaryDescription}</p><div className="mt-9 grid sm:grid-cols-2 gap-5">{restaurant.about.pillars.map(pillar => { const Icon = icons[pillar.icon]; return <div key={pillar.title} className="flex gap-3"><span className="w-10 h-10 rounded-xl bg-primary/20 flex items-center justify-center shrink-0"><Icon size={18} className="text-heading"/></span><div><p className="text-heading font-bold text-sm">{pillar.title}</p><p className="text-muted text-xs mt-1 leading-relaxed">{pillar.description}</p></div></div>; })}</div></div>
  <div className="relative h-[360px] sm:h-[500px]"><div className="absolute inset-[6%_0_0_7%] rounded-[2rem] bg-primary" aria-hidden="true"/><FallbackImage src={restaurant.about.primaryImage} fallbackSrc={restaurant.about.primaryImageFallback} alt={restaurant.about.primaryImageAlt} loading="lazy" className="relative w-[96%] h-[94%] object-cover rounded-[2rem] shadow-xl"/></div>
  </div></section>; }
