import { useState } from 'react';
import { ArrowRight, ChevronUp } from 'lucide-react';
import { restaurant } from '../../config/restaurant';
import { featuredMenuItems, homepageCategories, menu } from '../../data/menu';
import { SectionHeading } from '../ui/SectionHeading';
export function MenuSection() {
  const [showFullMenu, setShowFullMenu] = useState(false);
  return <section id="menu" className="bg-background-alt py-20 sm:py-24 px-5"><div className="max-w-7xl mx-auto">
    <div className="text-center mb-12"><SectionHeading eyebrow={restaurant.menu.eyebrow} heading={restaurant.menu.heading} description={restaurant.menu.description} /></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-5">{homepageCategories.map(category => <button key={category.id} onClick={() => { setShowFullMenu(true); setTimeout(() => document.getElementById(`category-${category.id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50); }} className="group relative min-h-44 sm:min-h-56 overflow-hidden rounded-2xl text-left shadow-sm focus-visible:outline focus-visible:outline-4 focus-visible:outline-primary"><img src={category.image} alt={`Catégorie ${category.name}`} loading="lazy" className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"/><span className="absolute inset-0 bg-gradient-to-t from-heading/80 via-heading/5 to-transparent"/><span className="absolute bottom-0 p-4 sm:p-5 text-white font-display font-black text-base sm:text-xl">{category.name}</span></button>)}</div>
    <h3 id="specialites" className="font-display text-2xl sm:text-3xl font-black text-heading mt-16 mb-6 scroll-mt-24">{restaurant.menu.popularHeading}</h3>
    <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{featuredMenuItems.slice(0,4).map(menuItem => <article key={menuItem.id} className="bg-surface rounded-2xl border border-border overflow-hidden hover:-translate-y-1 hover:shadow-lg transition-all"><img src={menuItem.image} alt={menuItem.name} loading="lazy" className="h-44 w-full object-cover"/><div className="p-5 flex items-start justify-between gap-4"><h4 className="font-bold text-heading">{menuItem.name}</h4><span className="font-black text-accent whitespace-nowrap">{menuItem.price}</span></div></article>)}</div>
    <div className="text-center mt-10"><button onClick={() => setShowFullMenu(!showFullMenu)} aria-expanded={showFullMenu} className="btn-primary">{showFullMenu ? 'Réduire le menu' : restaurant.menu.fullMenuCTA}{showFullMenu ? <ChevronUp size={17} className="inline ml-2"/> : <ArrowRight size={17} className="inline ml-2"/>}</button></div>
    {showFullMenu && <div id="full-menu" className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 mt-12 scroll-mt-24">{menu.categories.map(category => <article id={`category-${category.id}`} key={category.id} className="bg-surface border border-border rounded-2xl p-5 sm:p-6 scroll-mt-28"><h3 className="font-display text-xl font-black text-heading pb-4 border-b border-border">{category.name}</h3><ul className="mt-3 divide-y divide-border">{category.items.map(menuItem => <li key={menuItem.id} className="py-3"><div className="flex justify-between gap-3"><span className="font-semibold text-heading text-sm">{menuItem.name}</span><span className="font-black text-accent text-sm whitespace-nowrap">{menuItem.price}</span></div>{menuItem.description && <p className="text-muted text-xs mt-1">{menuItem.description}</p>}</li>)}</ul></article>)}</div>}
  </div></section>;
}
