import type { RestaurantConfig } from '../types/restaurant';

export const restaurant: RestaurantConfig = {
  businessName: 'EMBER',
  shortName: 'EMBER',
  tagline: 'Premium Burgers & Craft Takeaway',
  description: 'Premium cuts, bold spices, and sauces crafted from scratch.',
  logo: '/images/logo/logo.webp',
  favicon: '/vite.svg',
  phone: '+441234567890',
  phoneDisplay: '+44 (0) 20 7123 4567',
  email: 'hello@ember.example',
  address: '42 Brick Lane, Shoreditch',
  city: 'London',
  postcode: 'E1 6RF',
  country: 'United Kingdom',
  googleMapsUrl: 'https://maps.google.com/?q=42+Brick+Lane+London+E1+6RF',
  openingHours: [{ label: 'Mon–Sun', value: '11:30am – 10:30pm' }],
  social: { instagram: '#', facebook: '#', tiktok: '#' },
  ordering: { uberEats: '', deliveroo: '', clickAndCollect: '#contact', whatsapp: '' },
  navigation: ['Menu', 'About', 'Gallery', 'Reviews', 'Contact'],
  hero: {
    eyebrow: 'Craft Burgers · Handmade Daily',
    heading: 'Fire-Kissed',
    highlightedHeading: 'Flavour',
    description: 'Premium cuts, bold spices, and sauces crafted from scratch — every burger is built to be unforgettable.',
    primaryCTA: 'Explore Menu',
    secondaryCTA: 'Order Pickup',
    image: 'https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=1600',
    imageAlt: 'Hero burger',
    stats: [
      { label: 'Burgers Served', value: '50K+' }, { label: 'Avg. Rating', value: '4.9★' },
      { label: 'Locations', value: '3 Sites' }, { label: 'Years Running', value: 'Since 2018' },
    ],
  },
  menu: {
    eyebrow: 'Our Menu', heading: 'Crafted with Fire',
    description: 'Every burger starts with hand-selected beef, freshly baked brioche buns, and sauces made in-house each morning.',
    fullMenuCTA: 'View Full Menu',
  },
  about: {
    eyebrow: 'Our Story', heading: 'Born from a love of', highlightedHeading: 'real flavour',
    description: "Ember started in 2018 with a simple belief: a great burger doesn't need a gimmick. It needs quality beef, heat, and patience. Our founder Marcus spent two years perfecting the smash technique before opening our first hatch in Shoreditch.",
    secondaryDescription: 'Today we run three London kitchens, but every patty is still pressed by hand, every sauce made fresh each morning, and every bun baked by our bakery partner down the road.',
    primaryImage: 'https://images.pexels.com/photos/2282532/pexels-photo-2282532.jpeg?auto=compress&cs=tinysrgb&w=700', primaryImageAlt: 'Kitchen action',
    secondaryImage: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=400', secondaryImageAlt: 'Interior',
    experienceValue: '7+', experienceLabel: 'Years of Craft',
    pillars: [
      { icon: 'flame', title: 'Flame Grilled', description: 'Every patty is cooked over live flame for that unmistakable char.' },
      { icon: 'leaf', title: 'Fresh Sourced', description: 'Local butchers. Seasonal produce. No compromises.' },
      { icon: 'award', title: 'Award Winning', description: "Voted London's best burger 3 years running." },
      { icon: 'truck', title: 'Fast Delivery', description: "Hot to your door in 30 minutes or it's free." },
    ],
  },
  gallery: { eyebrow: 'Gallery', heading: 'Food Worth Looking At' },
  reviews: { eyebrow: 'Reviews', heading: 'What People Say', summary: '4.9 / 5 from 2,400+ reviews' },
  contact: { eyebrow: 'Find Us', heading: 'Come find your', highlightedHeading: 'next favourite', description: "Walk in or pre-order. We're open 7 days a week and deliver within 3 miles of each location." },
  booking: { heading: 'Book a Table', description: "Fill in below and we'll confirm within the hour.", submitLabel: 'Send Booking Request', successHeading: 'Booking Received!', successDescription: "We'll be in touch shortly to confirm your reservation." },
  footer: { tagline: 'Premium Burgers & Craft Takeaway', businessText: 'Ember Restaurants Ltd.', rightsText: 'All rights reserved.' },
  sections: { hero: true, menu: true, about: true, gallery: true, reviews: true, order: false, contact: true },
  seo: { title: 'EMBER — Premium Burgers & Craft Takeaway', description: 'Fire-kissed craft burgers handmade daily in London.', keywords: 'burgers, craft burgers, takeaway, London, Ember', ogImage: 'https://bolt.new/static/og_default.png' },
};
